export const environment = {
  production: true,
  staging: false,
  irBasePath: 'https://api.aivn.kr',
  irProvider: 'AIVeNautics',
  irContact: 'contact@aivenautics.com',
  oidcBasePath: 'https://maritimeid.aivn.kr',
  hasServiceRegistry: true,
  srBasePath: 'https://msr.aivn.kr',
  srProvider: 'AIVeNautics',
  srContact: 'contact@aivenautics.com',
  hasMSRLedger: false,
  ledgerPath: '',
  mpProvider: 'AIVeNautics',
  mpContact: 'contact@aivenautics.com',
  mpName: 'AIVeNautics MCP',
  environmentTitle: 'Production',
  termsOfUse: 'By applying for access to the MCP service of AIVeNautics, you agree not to store any personal information on the platform such as names and email addresses. Please use generic names, such as \'John Doe\' and generic email addresses such as \'info@company.com\'. It does need to be a working email address though, since access will be granted through this email address. Furthermore, if anyone chooses to federate an identity registry, this should only contain test data - not actual personal information. This is due to the European Union General Data Protection Regulation (GDPR). For more information, contact to contact@dmc.international.',
  idpNamespace: 'aivenautics',
  environmentName: 'production',
  footerName: 'AIVeNautics, 2024',
  footerLink: 'https://aivenautics.com/',
  logoImg: 'assets/images/aivn_logo.png',
  loginBgImg: '',
}
